version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/ruby:3.0-bullseye
    volumes:
      - .:/workspaces/yogocalc:cached
    working_dir: /workspaces/yogocalc
    command: sleep infinity
    network_mode: service:db
    environment:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: YOGO@1512
      DB_NAME: yogocalc_development
      DB_NAME_TEST: yogocalc_test

  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: YOGO@1512
      MYSQL_DATABASE: yogocalc_development
      MYSQL_USER: yogocalc
      MYSQL_PASSWORD: YOGO@1512
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
